export const EXERCISES: string[] = [
  'Bench Press',
  'Incline Bench Press',
  'Decline Bench Press',
  'Push Up',
  'Dumbbell Fly',
  'Cable Fly',
  'Squat',
  'Front Squat',
  'Leg Press',
  'Leg Extension',
  'Leg Curl',
  'Romanian Deadlift',
  'Deadlift',
  'Sumo Deadlift',
  'Hip Thrust',
  'Lunge',
  'Calf Raise',
  'Pull Up',
  'Lat Pulldown',
  'Seated Row',
  'Bent Over Row',
  'T-Bar Row',
  'Face Pull',
  'Shoulder Press',
  'Arnold Press',
  'Lateral Raise',
  'Front Raise',
  'Rear Delt Fly',
  'Shrug',
  'Bicep Curl',
  'Hammer Curl',
  'Preacher Curl',
  'Incline Curl',
  'Tricep Pushdown',
  'Skull Crusher',
  'Overhead Tricep Extension',
  'Dips',
  'Plank',
  'Ab Wheel',
  'Crunch',
  'Leg Raise',
  'Russian Twist',
  'Cable Crunch',
  "Farmer's Walk",
  'Battle Ropes',
  'Box Jump',
  'Burpee',
  'Mountain Climber',
  'Jumping Jack',
  'Jump Rope',
]
